---
id: myna-15th
base_name: mroonga
tags:
- rabbit
- mroonga
- mysql
- groonga
presentation_date: 2015-10-30
version: 2015.10.30.1
licenses:
- CC BY-SA 4.0
slideshare_id: myna-15th
speaker_deck_id: 
ustream_id: 
vimeo_id: 
youtube_id: 
author:
  markup_language: :rd
  name: Kouhei Sutou
  email: kou@clear-code.com
  rubygems_user: kou
  slideshare_user: kou
  speaker_deck_user: kou
